name: GitHub Builder and Tester

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      built: ${{ steps.build.outputs.cache }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4'

      - name: Install dependencies
        run: npm install

      - name: Build project
        id: build
        run: npm run build

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: ./dist
          key: ${{ runner.os }}-build-${{ hashFiles('dist/**') }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.4'

      - name: Restore build cache
        uses: actions/cache@v2
        with:
          path: ./dist
          key: ${{ runner.os }}-build-${{ hashFiles('dist/**') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
